### ISSUE TITLE
Model args are preserved across state resets

### ISSUE THREAD

**Issue by mbossenbroek** [czan/stateful-check#2]
I was trying to test a model and came across the following behavior. I'm not sure if this is the intended behavior, or if there's a better way to test this, or if my model isn't testable using this framework. Any suggestions are welcome.

The model is described as follows. I have a hashset that I can add nodes to. If a node is present in the set, I can request it and it will be returned. If the node has not been added, a request for it will throw an exception. There are two types of operations, one to add a node and one to request a node. These can be batched together such that multiple operations can be applied to the model at the same time. The expected behavior is to add all of the nodes first, and then evaluate any requests in the batch.

Now, for some examples...

``` clj
; adds node 1
(model/apply [{:type :node, :id 1}])
; request node 1; all is ok
(model/apply [{:type :request, :id 1}])

; request node 2; throws exception because it doesn't exist
(model/apply [{:type :request, :id 2}])

; re-request node 1; add node 3 & immediately request it, all ok because nodes are added first
(model/apply [{:type :request, :id 1} {:type :request, :id 3} {:type :node, :id 3}])
```

Here's a gist with repro code and output: https://gist.github.com/mbossenbroek/b3eb82d7dd19d7dfbea5

When setting up the test, I'm storing the set of nodes that should be in the model within the state. I'm then using that information in the state to generate a set of requests for only those nodes. To say it another way, these generators should only ever generate requests for nodes that are in the model (and the state).

What I'm seeing is that it's preserving the `:model/args` generators across state/model resets. It will do a run that adds node 2, requests node 2, and all is good. Then it will reset the model & state, but continue to use a generator that thinks the model has a node 2, and comes up with a failure case of requesting only node 2. This isn't valid because we know the model doesn't have a node 2, so the exception is expected.

So, the primary question seems to be: why is it using an older generator? Is that a bug, or am I modeling it incorrectly?

Some secondary questions:

Why does it call the `:initial-state` function so often? It calls it much more frequently and in more places than I would expect.

The final output/failure shows what appears to be step #<3> in the process, which is odd. I was expecting a sequence of operations to apply to the model, starting with #<1>. If there's only one step, why #<3>?

``` clj
FAIL in clojure.lang.PersistentList$EmptyList@1 (NO_SOURCE_FILE:1)
   #<3> = (:add-ops #{} [{:type :request, :id 0}])  =!!> #<AssertionError java.lang.AssertionError: Assert failed: (contains? m (:id op))>
Exception thrown while executing command 
Seed:  1445446106195
Visited:  14
```

Thanks,
Matt

**Comment by czan** [comment]
Hey Matt!

It looks like what you're running into is a shrinking problem. In essence, both arguments are shrunk independently which is resulting in them breaking.

So, for example:
  `([:node 4] [:request 4])` (which is valid)
can be shrunk to:
  `([:request 4])` (which is invalid)
which can be shrunk to:
  `([:request 0])` (which is the minimal invalid case)

You can fix this by adding a precondition to your command. This will then ignore the invalid shrink cases.

I found your code to be quite confusing. Particularly the way you're using the state: are you tracking the actual values of the "system" itself using the stateful-check abstract state? If so: don't do that. Your actual "system" should have its own state, and the abstract state should be modelling it.

Due to my confusion, I have re-written your example to be in line with how I interpreted your specification. You can see my code here: https://gist.github.com/czan/94a32ca5e10f5fb83b76. I've also re-written it to actually perform a test by using an external atom to hold the state of the "system" you're testing.

Now to your other questions:
- The `:initial-state` function will be called at least twice for each run: once to generate the list of commands and once for the actual command execution. Additionally, it will be called every time we need to check whether a list of commands is valid, which can happen fairly often.
- Shrinking is also why the final output starts with command `#<3>`. Originally it would have been a sequence `#<0>`, `#<1>`, `#<2>`, `#<3>`, ..., but during shrinking it found that the first three commands it had generated did not provoke a failure, so it just removed them from the execution.

**Comment by mbossenbroek** [comment]
Awesome! I was hoping it was something simple like that. The atom thing was a result of me simplifying our actual system - that was just a rewrite mistake. We do have something that actually has a state that we're trying to test - not just a simple hashset :)

One followup question though: The queue example in your docs has the state maintaining a reference to the 'queue' which contains an atom. Your rewrite of my example has it as a global. Is there any difference? The former seems more sanitary to me.

Guess I need to read up on the specification docs some more too... thanks for the tip on the preconditions!

**Comment by czan** [comment]
If possible, definitely go for holding the reference in the state (ie. follow the queue example).

The example with the atom corresponds to something that has implicit global state, but if you can avoid having state like that then you're better off. I just did it that way for the example because I didn't want to assume that you could capture the stateful object directly (and also because it was easier to do without having to think too hard).
