### ISSUE TITLE
Update for test.check 0.9.0

### ISSUE THREAD

**Issue by MichaelDrogalis** [czan/stateful-check#5]
Hi there! Thanks for this wonderful tool!

It appears that using it in conjunction with test.check 0.9.0 throws incompatibility errors. Running the test suite for stateful-check produces an exception that IPersistentVector can't be cast to a RoseTree. I did some digging around, but wasn't able to come up with a solution.

**Comment by czan** [comment]
Well, it's taken over two years, but it now works with test.check 0.9.0. Unfortunately, because I've made some quite drastic changes, it's likely that any code written against the previous version will need to be updated to work with 0.4.0.

Based on a quick look through the Onyx code base, though, it doesn't look like stateful-check is being used any more, so I guess that's not a problem for you.

Either way, I'm closing this issue. Sorry for the delay!

**Comment by MichaelDrogalis** [comment]
Thanks @czan :)
