### ISSUE TITLE
How to generate args based on system-generated data.

### ISSUE THREAD

**Issue by dmarjenburgh** [czan/stateful-check#9]
Let's say you are testing a system where records are stored and the system assigns and returns a generated id. You can get back records by their id.

During `retrieve-record` command args generation, I want to randomly pick one of the generated ids, but the :args fn works on symbolic values and then the system will get called with a symbolic value.

How can you make this work?

**Comment by czan** [comment]
I don't quite understand your question, but I've tried to implement something that hopefully will answer your question.

To start with, I built a small "system" that allows you to store records, and then later to retrieve them. It's pretty much as simple as I could make it while doing that.

```clojure
(def records (atom {}))

(defn store-record [value]
  (let [id (gensym "id")]
    (swap! records assoc id value)
    id))

(defn retrieve-record [id]
  (get @records id))
```

Then, I wanted to implement some command specifications for these. To start I required some things that I would need.

```clojure
(require '[stateful-check.core :refer [specification-correct?]]
         '[clojure.test.check.generators :as gen]
         '[clojure.test :refer [is]])
```

Now, on to the command specs. The first is `store-record`. It generates an int to use as a value, and then calls `store-record`. The `:next-state` records the id that is returns into the state object (note that during command generation this is a symbolic value).

```clojure
(def store-record-spec
  {:args (fn [_] [gen/int])
   :command #'store-record
   :next-state (fn [state [value] id]
                 (assoc state id value))})
```

The second is `retrieve-record`. We use `gen/elements`, so we need to `:requires` that we expect something in the map, otherwise we'll get an exception. The key of the `state` object in `:args` will all be symbolic values, but the symbolic value in the arguments will be replaced by a concrete id during command execution. The `:postcondition` is run after command execution has finished, and checks that the value that we have retrieved corresponds to the one that we expected to get back out of the state map.

```clojure
(def retrieve-record-spec
  {:requires seq
   :args (fn [state]
           [(gen/elements (keys state))])
   :command #'retrieve-record
   :postcondition (fn [state _ [id] value]
                    (= (get state id)
                       value))})
```

If we run this system we will see that `specification-correct?` returns true, because the specification accurately models the system.

```clojure
(is (specification-correct?
     {:commands {:store #'store-record-spec
                 :retrieve #'retrieve-record-spec}}))
```

Please let me know if anything is unclear in that explanation, or if you need any more help. :smiley:

**Comment by dmarjenburgh** [comment]
Hi Czan,

Thanks a lot for such a fast and detailed answer! 😃

Apologies if my explanation was unclear.
In my setup, the system returned a pair of `[<status-code> <data>]`upon `store-record` and the <data> has an `:id`. I had some trouble getting the id value out of the result and the failure displayed the command as: `(:retrieve-record (get <#1> 1))`. In the end it turned out to be an error in my code as it is working now with the help of your example.

Again, thanks for the fast and detailed help. I appreciate it.

**Comment by czan** [comment]
Good to hear you got it working!

In terms of reading the output, the `(get #<1> 1)` is indicating that the value used there is the result of calling `get` on the result of the first command (ie. look for `#<1> = (... some command ...) = ... some value ...` earlier in the command sequence).

As an example, I modified my `store-record` function from above to return a `[value id]` vector, and modified the other functions/commands to match, then intentionally broke the `retrieve-record` function. This is the output that I got:

```
  #<1> = (:store 0)  = [0 id14924]
  #<2> = (:retrieve (get #<1> 1))  = nil
```

See how the second command uses `(get #<1> 1)` as its argument. Given `#<1> = ... = [0 id14924]`, that means that the argument is equivalent to `(get [0 id14924] 1)` which is just `id14924`.

It's also possible to have more layers, like if I had also wrapped the id in a map like `{:id id}` then it starts to get a bit messier:

```
  #<1> = (:store 0)  = [0 {:id id15003}]
  #<2> = (:retrieve (get (get #<1> 1) :id))  = nil
```
